spring.application.name=chat_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp_db
spring.datasource.username=postgres
spring.datasource.password=recyclebin

spring.jpa.hibernate.ddl-auto=update

